[package]
name = "analise-redes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.4"
flate2 = "1.0.30"
rayon = "1.9.0"
plotters = "0.3.6"